name: ARIFPAKTIGER2021

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download OpenVPN
      run: |
        $latestRelease = Invoke-RestMethod -Uri "https://api.github.com/repos/OpenVPN/openvpn/releases/latest"
        $installerUrl = $latestRelease.assets | Where-Object { $_.name -like "*installer.exe" } | Select-Object -First 1 -ExpandProperty browser_download_url
        Invoke-WebRequest -Uri $installerUrl -OutFile OpenVPN.exe

    - name: Install OpenVPN
      run: Start-Process -FilePath .\OpenVPN.exe -ArgumentList '/S' -Wait

    - name: Start OpenVPN
      run: Start-Process -FilePath 'C:\Program Files\OpenVPN\bin\openvpn.exe' -ArgumentList '--config', 'xama.first.ovpn' -Wait

    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Forward Port 3389
      run: |
        New-NetFirewallRule -DisplayName "RDP Allow" -Direction Inbound -Protocol TCP -LocalPort 3389 -Action Allow
