name: ARIFPAKTIGER2021

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download OpenVPN Connect
      run: |
        Invoke-WebRequest -Uri https://openvpn.net/downloads/openvpn-connect-v3-windows.msi -OutFile OpenVPNConnect.msi

    - name: Install OpenVPN Connect
      run: Start-Process -FilePath msiexec.exe -ArgumentList '/i', 'OpenVPNConnect.msi', '/quiet', '/norestart' -Wait

    - name: Start OpenVPN
      run: Start-Process -FilePath 'C:\Program Files\OpenVPN Connect\OpenVPNConnect.exe' -ArgumentList '--config', 'xama.first.ovpn' -Wait

    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Forward Port 3389
      run: |
        New-NetFirewallRule -DisplayName "RDP Allow" -Direction Inbound -Protocol TCP -LocalPort 3389 -Action Allow
